# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\"\t\n\x07GetInfo\"$\n\x07SaveKey\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x17\n\x08RemFiKey\x12\x0b\n\x03key\x18\x01 \x01(\t\")\n\rGetChordReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\"\x1d\n\x0cGetNodeReply\x12\r\n\x05table\x18\x01 \x03(\x05\"&\n\tSaveReply\x12\r\n\x05saved\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\"*\n\x0bRemoveReply\x12\x0f\n\x07removed\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\"&\n\tFindReply\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x32\xbb\x01\n\rSimpleService\x12&\n\x08GetChord\x12\x08.GetInfo\x1a\x0e.GetChordReply0\x01\x12\"\n\x07GetNode\x12\x08.GetInfo\x1a\r.GetNodeReply\x12\x1c\n\x04Save\x12\x08.SaveKey\x1a\n.SaveReply\x12!\n\x06Remove\x12\t.RemFiKey\x1a\x0c.RemoveReply\x12\x1d\n\x04\x46ind\x12\t.RemFiKey\x1a\n.FindReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETINFO._serialized_start=15
  _GETINFO._serialized_end=24
  _SAVEKEY._serialized_start=26
  _SAVEKEY._serialized_end=62
  _REMFIKEY._serialized_start=64
  _REMFIKEY._serialized_end=87
  _GETCHORDREPLY._serialized_start=89
  _GETCHORDREPLY._serialized_end=130
  _GETNODEREPLY._serialized_start=132
  _GETNODEREPLY._serialized_end=161
  _SAVEREPLY._serialized_start=163
  _SAVEREPLY._serialized_end=201
  _REMOVEREPLY._serialized_start=203
  _REMOVEREPLY._serialized_end=245
  _FINDREPLY._serialized_start=247
  _FINDREPLY._serialized_end=285
  _SIMPLESERVICE._serialized_start=288
  _SIMPLESERVICE._serialized_end=475
# @@protoc_insertion_point(module_scope)
